import type { Security } from "../../models/Security";

export const mockSecurities: Security[] = [
  {
    id: "1",
    ticker: "AAPL",
    isin: "US0378331005",
    market: "NASDAQ",
    quantity: 100,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "2",
    ticker: "MSFT",
    isin: "US5949181045",
    market: "NASDAQ",
    quantity: 200,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "3",
    ticker: "GOOGL",
    isin: "US02079K3059",
    market: "NASDAQ",
    quantity: 150,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "4",
    ticker: "AMZN",
    isin: "US0231351067",
    market: "NASDAQ",
    quantity: 80,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "5",
    ticker: "TSLA",
    isin: "US88160R1014",
    market: "NASDAQ",
    quantity: 50,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
];
