import type { Security } from "../components/models/Security";

export const mockSecurities: Security[] = [
  {
    id: "1",
    ticker: "AAPL",
    isin: "US0378331005",
    market: "NASDAQ",
    quantity: 100,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "2",
    ticker: "MSFT",
    isin: "US5949181045",
    market: "NASDAQ",
    quantity: 200,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "3",
    ticker: "GOOGL",
    isin: "US02079K3059",
    market: "NASDAQ",
    quantity: 150,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "4",
    ticker: "AMZN",
    isin: "US0231351067",
    market: "NASDAQ",
    quantity: 80,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "5",
    ticker: "TSLA",
    isin: "US88160R1014",
    market: "NASDAQ",
    quantity: 50,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "6",
    ticker: "NVDA",
    isin: "US67066G1040",
    market: "NASDAQ",
    quantity: 120,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "7",
    ticker: "META",
    isin: "US30303M1027",
    market: "NASDAQ",
    quantity: 90,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "8",
    ticker: "BRK.B",
    isin: "US0846707026",
    market: "NYSE",
    quantity: 40,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "9",
    ticker: "JPM",
    isin: "US46625H1005",
    market: "NYSE",
    quantity: 75,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "10",
    ticker: "V",
    isin: "US92826C8394",
    market: "NYSE",
    quantity: 110,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "11",
    ticker: "JNJ",
    isin: "US4781601046",
    market: "NYSE",
    quantity: 65,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "12",
    ticker: "WMT",
    isin: "US9311421039",
    market: "NYSE",
    quantity: 140,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "13",
    ticker: "PG",
    isin: "US7427181091",
    market: "NYSE",
    quantity: 95,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "14",
    ticker: "DIS",
    isin: "US2546871060",
    market: "NYSE",
    quantity: 70,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "15",
    ticker: "BAC",
    isin: "US0605051046",
    market: "NYSE",
    quantity: 130,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "16",
    ticker: "XOM",
    isin: "US30231G1022",
    market: "NYSE",
    quantity: 55,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "17",
    ticker: "NFLX",
    isin: "US64110L1061",
    market: "NASDAQ",
    quantity: 45,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "18",
    ticker: "PEP",
    isin: "US7134481081",
    market: "NASDAQ",
    quantity: 85,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "19",
    ticker: "KO",
    isin: "US1912161007",
    market: "NYSE",
    quantity: 160,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "20",
    ticker: "NKE",
    isin: "US6541061031",
    market: "NYSE",
    quantity: 60,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "21",
    ticker: "INTC",
    isin: "US4581401001",
    market: "NASDAQ",
    quantity: 170,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "22",
    ticker: "CRM",
    isin: "US79466L3024",
    market: "NYSE",
    quantity: 35,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "23",
    ticker: "ORCL",
    isin: "US68389X1054",
    market: "NYSE",
    quantity: 125,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "24",
    ticker: "CSCO",
    isin: "US17275R1023",
    market: "NASDAQ",
    quantity: 145,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "25",
    ticker: "ABNB",
    isin: "US0090661010",
    market: "NASDAQ",
    quantity: 30,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "26",
    ticker: "PYPL",
    isin: "US70450Y1038",
    market: "NASDAQ",
    quantity: 115,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "27",
    ticker: "ADBE",
    isin: "US00724F1012",
    market: "NASDAQ",
    quantity: 105,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "28",
    ticker: "TM",
    isin: "JP3633400001",
    market: "NYSE",
    quantity: 52,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "29",
    ticker: "BABA",
    isin: "US01609W1027",
    market: "NYSE",
    quantity: 95,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "30",
    ticker: "RDS.A",
    isin: "GB00B03MLX29",
    market: "NYSE",
    quantity: 40,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "31",
    ticker: "SAP",
    isin: "DE0007164600",
    market: "NYSE",
    quantity: 78,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "32",
    ticker: "SONY",
    isin: "JP3435000009",
    market: "NYSE",
    quantity: 66,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "33",
    ticker: "BMY",
    isin: "US09662Q1040",
    market: "NYSE",
    quantity: 98,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "34",
    ticker: "T",
    isin: "US00206R1023",
    market: "NYSE",
    quantity: 180,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "35",
    ticker: "VZ",
    isin: "US92343V1044",
    market: "NYSE",
    quantity: 155,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "36",
    ticker: "UPS",
    isin: "US9113121068",
    market: "NYSE",
    quantity: 60,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "37",
    ticker: "MCD",
    isin: "US5801351017",
    market: "NYSE",
    quantity: 89,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "38",
    ticker: "SBUX",
    isin: "US8552441094",
    market: "NASDAQ",
    quantity: 57,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "39",
    ticker: "CVX",
    isin: "US1667641005",
    market: "NYSE",
    quantity: 102,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "40",
    ticker: "GE",
    isin: "US3696041033",
    market: "NYSE",
    quantity: 200,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "41",
    ticker: "NFLX",
    isin: "US64110L1061",
    market: "NASDAQ",
    quantity: 34,
    comments: "",
    giftType: "",
    cusip: "",
    description: "Duplicate ticker sample",
  },
  {
    id: "42",
    ticker: "UNH",
    isin: "US91324P1021",
    market: "NYSE",
    quantity: 68,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "43",
    ticker: "LLY",
    isin: "US5364571083",
    market: "NYSE",
    quantity: 74,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "44",
    ticker: "MRK",
    isin: "US5893311077",
    market: "NYSE",
    quantity: 82,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "45",
    ticker: "ABBV",
    isin: "US00287Y1091",
    market: "NYSE",
    quantity: 96,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "46",
    ticker: "ACN",
    isin: "IE00B4BNMY34",
    market: "NYSE",
    quantity: 88,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "47",
    ticker: "ADP",
    isin: "US00651W1099",
    market: "NASDAQ",
    quantity: 53,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "48",
    ticker: "ZM",
    isin: "US98980L1017",
    market: "NASDAQ",
    quantity: 37,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "49",
    ticker: "SQ",
    isin: "US8522341036",
    market: "NYSE",
    quantity: 121,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "50",
    ticker: "DOCU",
    isin: "US2561631068",
    market: "NASDAQ",
    quantity: 49,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "51",
    ticker: "SNAP",
    isin: "US83304A1060",
    market: "NYSE",
    quantity: 99,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "52",
    ticker: "PFE",
    isin: "US7170811035",
    market: "NYSE",
    quantity: 125,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "53",
    ticker: "TMO",
    isin: "US8716071076",
    market: "NYSE",
    quantity: 58,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "54",
    ticker: "LOW",
    isin: "US5486611073",
    market: "NYSE",
    quantity: 76,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
  {
    id: "55",
    ticker: "CVS",
    isin: "US1266501006",
    market: "NYSE",
    quantity: 63,
    comments: "",
    giftType: "",
    cusip: "",
    description: "",
  },
];
